{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"SUN",
            "address":"TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9",
            "chainId":1,
            "decimals":18,
            "name":"SUN TOKEN",
            "logoURI":"https://coin.top/production/logo/SUNLogo.178d4636.png"
        },
        {
            "symbol":"BTC",
            "address":"TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
            "chainId":1,
            "decimals":8,
            "name":"Bitcoin",
            "logoURI":"https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
        },
        {
            "symbol":"ETH",
            "address":"THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF",
            "chainId":1,
            "decimals":18,
            "name":"Ethereum",
            "logoURI":"https://coin.top/production/logo/THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF.png"
        },
        {
            "symbol":"JST",
            "address":"TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9",
            "chainId":1,
            "decimals":18,
            "name":"JUST GOV v1.0",
            "logoURI":"https://coin.top/production/logo/just_icon.png"
        },
        {
            "symbol":"YunH",
            "address":"TVHLxwSekSseGBQdr6iLVF7C7eXo1uoQgr",
            "chainId":1,
            "decimals":6,
            "name":"YunH Token",
            "logoURI":"https://github.com/67112597/justlists/blob/main/TVHLxwSekSseGBQdr6iLVF7C7eXo1uoQgr.png"
        },
        {
            "symbol":"USDT",
            "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        },
        {
            "symbol":"LTC",
            "address":"TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd",
            "chainId":1,
            "decimals":8,
            "name":"Litecoin",
            "logoURI":"https://coin.top/production/logo/TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd.png"
        },
        {
            "symbol":"HT",
            "address":"TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h",
            "chainId":1,
            "decimals":18,
            "name":"HuobiToken",
            "logoURI":"https://coin.top/production/logo/TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h.png"
        }
    ],
    "logoURI":"https://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}
